<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
#autogenerated
Route::resource('buildings', 'Api\BuildingsController', ['except' => ['create', 'edit']]);
Route::resource('equipment', 'Api\EquipmentController', ['except' => ['create', 'edit']]);
Route::resource('disciplines', 'Api\DisciplinesController', ['except' => ['create', 'edit']]);
Route::resource('classes', 'Api\ClassesController', ['except' => ['create', 'edit']]);
Route::resource('classrooms', 'Api\ClassroomsController', ['except' => ['create', 'edit']]);
Route::resource('hours', 'Api\HoursController', ['except' => ['create', 'edit']]);
Route::resource('lessons', 'Api\LessonsController', ['except' => ['create', 'edit']]);
#endautogenerated